# 训练配置
restore_from: "../models/neutts-air"
data_files: "./dataset/train_data.jsonl"
save_root: "output/"
language: "cmn"

# 模型信息
codebook_size: 65536
max_seq_len: 2048
lr: 0.00004
lr_scheduler_type: "cosine"
warmup_ratio: 0.00

# 训练信息
per_device_train_batch_size: 2
num_train_epochs: 10
logging_steps: 100
save_steps: 20000
seed: 1337